import React, { useState } from 'react';
import { AlertTriangle, ShieldCheck, X, Info } from 'lucide-react';

export const DisclaimerBanner: React.FC = () => {
  const [showFullModal, setShowFullModal] = useState(false);

  return (
    <>
      <div id="sebi-disclaimer-banner" className="bg-[#111318] border border-amber-500/25 rounded-xl p-3 text-xs text-amber-200/90 flex items-start gap-3 shadow-inner">
        <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div className="flex-1 leading-relaxed text-[11px]">
          <span className="font-bold text-amber-300 mr-1.5 uppercase tracking-wide">SEBI STATUTORY MANDATE:</span>
          This platform provides quantitative algorithmic models, technical levels, and corporate fundamental data for 
          <strong className="text-amber-200 mx-1">EDUCATIONAL & RESEARCH USE ONLY</strong>. It is NOT certified investment advice under SEBI (Investment Advisers) Regulations, 2013. Consult a SEBI-registered advisor before executing capital transactions.
        </div>
        <button
          id="btn-view-sebi-terms"
          onClick={() => setShowFullModal(true)}
          className="shrink-0 text-[11px] text-amber-300 hover:text-amber-100 underline font-medium px-2 py-1 bg-amber-500/10 hover:bg-amber-500/20 rounded-md transition-colors whitespace-nowrap"
        >
          Full Disclaimer
        </button>
      </div>

      {showFullModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm">
          <div className="bg-[#111318] border border-slate-700 max-w-2xl w-full rounded-2xl p-6 shadow-2xl relative text-slate-200 animate-in fade-in zoom-in-95 duration-150">
            <button
              id="btn-close-sebi-modal"
              onClick={() => setShowFullModal(false)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3 mb-4 text-amber-400">
              <ShieldCheck className="w-6 h-6 text-amber-400" />
              <h2 className="text-lg font-bold tracking-tight text-white font-mono">
                Regulatory & Risk Mandate (NSE / BSE)
              </h2>
            </div>

            <div className="space-y-3.5 text-sm leading-relaxed text-slate-300 max-h-[70vh] overflow-y-auto pr-2">
              <div className="bg-[#08090b] p-3.5 rounded-xl border border-slate-800">
                <h3 className="font-semibold text-amber-300 text-xs uppercase tracking-wider mb-1 flex items-center gap-1.5">
                  <Info className="w-3.5 h-3.5" /> 1. Educational Market Intelligence
                </h3>
                <p className="text-xs text-slate-300">
                  The insights, automated price levels (Target 1, Target 2, Strict Stop-Loss), EMA crossovers, and signal classifications generated by this system are designed strictly for educational exploration, backtesting analysis, and quantitative research.
                </p>
              </div>

              <div className="bg-[#08090b] p-3.5 rounded-xl border border-slate-800">
                <h3 className="font-semibold text-amber-300 text-xs uppercase tracking-wider mb-1">
                  2. No SEBI Investment Advisory Relationship
                </h3>
                <p className="text-xs text-slate-300">
                  Neither the platform nor any underlying computational engine is registered with the Securities and Exchange Board of India (SEBI) as a Registered Investment Adviser (RIA) or Portfolio Manager (PMS). Use of this tool does not create any advisory or fiduciary relationship.
                </p>
              </div>

              <div className="bg-[#08090b] p-3.5 rounded-xl border border-slate-800">
                <h3 className="font-semibold text-amber-300 text-xs uppercase tracking-wider mb-1">
                  3. Risk of Capital Loss in Indian Equities & Derivatives
                </h3>
                <p className="text-xs text-slate-300">
                  Stock markets in India (NSE / BSE) fluctuate based on corporate earnings, macroeconomic indicators, foreign portfolio investment (FPI) flows, and monetary policy actions. Past performance and technical momentum do not guarantee future returns. Derivative trading (Futures & Options) entails extreme leverage risk.
                </p>
              </div>

              <div className="bg-[#08090b] p-3.5 rounded-xl border border-slate-800">
                <h3 className="font-semibold text-amber-300 text-xs uppercase tracking-wider mb-1">
                  4. User Responsibility & Verification
                </h3>
                <p className="text-xs text-slate-300">
                  Users must independently verify current market prices (CMP), exchange filings on NSE/BSE corporate portals, and audited financial statements before making any capital commitment.
                </p>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-slate-800 flex justify-end">
              <button
                id="btn-acknowledge-sebi"
                onClick={() => setShowFullModal(false)}
                className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl text-xs transition-all shadow-[0_0_15px_rgba(79,70,229,0.35)]"
              >
                I Understand & Acknowledge
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

